function CreateMasterDeck(){
    var MasterDeck = [];



MasterDeck.push(CreateCard("Bulbasaur", 180, 13, 15, 2, "Bulbasaur.png", "Grass"));
MasterDeck.push(CreateCard("Ivysaur", 280, 21, 25, 3, "Ivysaur.png", "Grass", "Poison"));
MasterDeck.push(CreateCard("Venusaur", 400, 30, 40, 4, "Venusaur.png", "Grass" , "Dragon"));
MasterDeck.push(CreateCard("Charmander", 140, 18, 13, 3, "Charmander.png", "Fire"));
MasterDeck.push(CreateCard("Charmeleon", 250, 28, 23, 4, "Charmeleon", "Fire" , "Fighting"));
MasterDeck.push(CreateCard("Charizard", 350, 42, 33, 6, "Charizard.png", "Fire" , "Dragon"));
MasterDeck.push(CreateCard("Squirtle", 160, 15, 18, 1, "Squirtle.png", "Water"));
MasterDeck.push(CreateCard("Wartortle", 260, 25, 28, 2, "Wartotle.png", "Water" , "Rock"));
MasterDeck.push(CreateCard("Blastoise", 380, 35, 45, 3, "Blastoise.png", "Water" , "Dragon"));
MasterDeck.push(CreateCard("Carterpie", 120, 10, 10, 1, "Caterpie.png", "Bug"));
MasterDeck.push(CreateCard("Metapod", 200, 15, 25, 1, "Metapod.png", "Bug"));
MasterDeck.push(CreateCard("Butterfree", 300, 27, 25, 3, "Butterfree.png", "Bug" , "Psychic"));
MasterDeck.push(CreateCard("Weedle", 120, 12, 8, 2, "Weedle.png", "Bug" , "Poison"));
MasterDeck.push(CreateCard("Kakuna", 200, 18, 25, 3, "Kakuna.png", "Bug" , "Poison"));
MasterDeck.push(CreateCard("Beedrill", 300, 25, 30, 3, "Beedrill.png", "Bug" , "Poison"));
MasterDeck.push(CreateCard("Pidgey", 140, 14, 14, 2, "Pidgey.png", "Flying"));
MasterDeck.push(CreateCard("Pideoto", 250, 21, 21, 3, "Pidgeoto.png", "Flying"));
MasterDeck.push(CreateCard("Pidgeot", 320, 35, 30, 5, "Pidgeot.png", "Flying" , "Dragon"));
MasterDeck.push(CreateCard("Rattata", 140, 13, 16, 2, "Rattata.png", "Normal"));
MasterDeck.push(CreateCard("Raticate", 250, 25, 26, 3, "Raticate.png", "Normal"));
MasterDeck.push(CreateCard("Spearow", 130, 14, 21, 2, "Spearow.png", "Flying"));
MasterDeck.push(CreateCard("Fearow", 280, 30, 34, 4, "Fearow.png", "Flying"));
MasterDeck.push(CreateCard("Ekans", 140, 15, 10, 3, "Ekans,png", "Poison"));
MasterDeck.push(CreateCard("Arbok", 250, 27, 25, 5, "Arbok.png", "Poison"));
MasterDeck.push(CreateCard("Pikachu", 170, 16, 15, 3, "Pikachu.png", "Electric"));
MasterDeck.push(CreateCard("Raichu", 300, 30, 30, 6, "Raichu.png", "Electric" , "Dragon"));
MasterDeck.push(CreateCard("Sandshrew", 150, 14, 20, 2, "Sandshrew.png", "Ground"));
MasterDeck.push(CreateCard("Sandslah", 250, 25, 35, 3, "Sandslash.png", "Ground"));
MasterDeck.push(CreateCard("Nidoran q", 140, 13, 15, 2, "Nidoranq.png", "Poison" , "Ground"));
MasterDeck.push(CreateCard("Nidorina", 240, 21, 25, 3, "Nidorina.png", "Poison" , "Ground"));
MasterDeck.push(CreateCard("Nidoqueen", 350, 30, 35, 4, "Nidoqueen.png", "Poison" , "Ground"));
MasterDeck.push(CreateCard("Nidoran c", 150, 14, 13, 3, "Nidoranc.png", "Ground"));
MasterDeck.push(CreateCard("Nidorino", 260, 26, 23, 4,  "Nidorino.png", "Ground" , "Poison"));
MasterDeck.push(CreateCard("Nidoking", 380, 35, 33, 5, "Nidoking.png", "Ground" , "Poison"));
MasterDeck.push(CreateCard("Clefairy", 160, 14, 20, 3, "Clefairy.png", "Psychic"));
MasterDeck.push(CreateCard("Clefable", 300, 25, 40, 5, "Clefable.png", "Psychic" , "Dragon"));
MasterDeck.push(CreateCard("Vulpix", 150, 15, 18, 3, "Vulpix.png", "Fire"));
MasterDeck.push(CreateCard("Ninetales", 280, 25, 38, 5, "Ninetales.png", "Fire" , "Psychic"));
MasterDeck.push(CreateCard("Jigglypuff", 160, 14, 24, 2,  "Jigglypuff.png", "Psychic"));
MasterDeck.push(CreateCard("Wigglytuff", 320, 25, 44, 4, "Wigglytuff.png", "Psychic" ));
MasterDeck.push(CreateCard("Zubat", 140, 15, 13, 3, "Zubat.png", "Poison" , "Flying" ));
MasterDeck.push(CreateCard("Golbat", 250, 25, 23, 4, "Golbat.png", "Poison" , "Flying"));
MasterDeck.push(CreateCard("Oddish", 150, 13, 16, 2, "Oddish.png", "Grass"));
MasterDeck.push(CreateCard("Gloom", 250, 20, 26, 3, "Gloom.png", "Poison" , "Grass"));
MasterDeck.push(CreateCard("Vileplume", 300, 28, 38, 4, "Vileplume.png", "Grass" , "Poison"));
MasterDeck.push(CreateCard("Paras", 150, 14, 16, 3, "Paras.png", "Bug" , "Grass"));
MasterDeck.push(CreateCard("Parasect", 300, 21, 30, 5, "Parasect.png", "Grass" , "Bug"));
MasterDeck.push(CreateCard("Venonat", 140, 13, 13, 2, "Venonat.png", "Bug" , "Poison"));
MasterDeck.push(CreateCard("Venomoth", 250, 21, 23, 4, "Venomoth.png", "Bug" , "Poison"));
MasterDeck.push(CreateCard("Diglett", 140, 13, 18, 2, "Diglett.png", "Ground"));
MasterDeck.push(CreateCard("Dugtrio", 280, 25, 30, 3, "Dugtrio.png", "Ground"));
MasterDeck.push(CreateCard("Meowth", 140, 15, 15, 3, "Meowth.png", "Normal" ));
MasterDeck.push(CreateCard("Persian", 250, 23, 30, 4, "Persian.png", "Normal"));
MasterDeck.push(CreateCard("Psyduck", 160, 13, 15, 2, "Psyduck.png", "Water"));
MasterDeck.push(CreateCard("Golduck", 250, 25, 25, 4, "Golduck.png", "Water" & "Psychic"));
MasterDeck.push(CreateCard("Mankey", 140, 16, 12, 3, "Mankey.png", "Fighting"));
MasterDeck.push(CreateCard("Primeape", 250, 30, 23, 5, "Primeape", "Fighting"));
MasterDeck.push(CreateCard("Growlithe", 150, 16, 13, 3, "Growlithe.png", "Fire"));
MasterDeck.push(CreateCard("Arcanine", 300, 30, 25, 6, "Arcanine.png", "Fire" & "Dragon"));
MasterDeck.push(CreateCard("Poliwag", 140, 14, 14, 2, "Poliwag.png", "Water"));
MasterDeck.push( CreatCard("Poliwhile", 250, 21, 21, 3, "Poliwhile.png", "Water"));
MasterDeck.push(CreateCard("Poliwrath", 300, 35, 30, 5, "Poliwrath.png", "Water" , "Fighting"));
MasterDeck.push(CreateCard("Abra", 130, 17, 12, 4, "Abra.png", "Psychic"));
MasterDeck.push(CreateCard("Kadabra", 250, 30, 21, 6, "Kadabra.png", "Psychic"));
MasterDeck.push(CreateCard("Alakazam", 350, 40, 30, 7, "Alakazam.png", "Psychic" , "Dragon"));
MasterDeck.push(CreateCard("Machop", 150, 16, 18, 2, "Machop.png", "Fighting"));
MasterDeck.push(CreateCard("Machoke", 280, 25, 30, 3, "Machoke.png", "Fighting"));
MasterDeck.push(CreateCard("Machamp", 350, 35, 40, 5, "Machamp.png", "Fighting" , "Rock"));
MasterDeck.push(CreateCard("Bellsprout", 150, 15, 15, 3, "Bellsprout.png", "Grass"));
MasterDeck.push(CreateCard("Weepinbell", 250, 20, 25, 4, "Weepinbell.png", "Grass"));
MasterDeck.push(CreateCard("Victribell", 350, 30, 30, 6, "Victribell.png", "Grass"));
MasterDeck.push(CreateCard("Tentacool", 140, 16, 13, 3, "Tentacool.png", "Water"));
MasterDeck.push(CreateCard("Tentacruel", 300, 28, 25, 5, "Tentacruel.png", "Water"));
MasterDeck.push(CreateCard("Geodude", 170, 15, 21, 2,  "Geodude.png", "Rock"));
MasterDeck.push(CreateCard("Graveller", 280, 21, 40, 3, "Graveller.png", "Ground"));
MasterDeck.push(CreateCard("Golem", 380, 32, 50, 4, "Golem.png", "Ground"));
MasterDeck.push(CreateCard("Ponyta", 150, 15, 15, 3, "Ponyta.png", "Fire"));
MasterDeck.push(CreateCard("Rapidash", 300, 32, 30, 5, "Rapidash.png", "Fire"));
MasterDeck.push(CreateCard("Slowpoke", 160, 14, 20, 3, "Slowpoke.png", "Water"));
MasterDeck.push(CreateCard("Slowbro", 300, 25, 40, 6, "Slowbro.png", "Psychic"));
MasterDeck.push(CreateCard("Magnemite", 160, 14, 25, 3, "Magnemite.png", "Electric"));
MasterDeck.push(CreateCard("Magneton", 300, 25, 45, 5, "Magneton.png", "Steel" ));
MasterDeck.push( CreateCard("Farfetched", 210, 21, 30, 6, "Farfetched.png", "Flying"));
MasterDeck.push(CreateCard("Doduo", 140, 15, 15, 3, "Doduo.png", "Flying"));
MasterDeck.push(CreateCard("Dodrio", 280, 25, 35, 5, "Dodrio.png", "Flying"));
MasterDeck.push(CreateCard("Seel", 160, 15, 20, 2, "Seel.png", "Ice"));
MasterDeck.push(CreateCard("Dewgong", 320, 25, 35, 4, "Dewgong.png", "Ice"));
MasterDeck.push(CreateCard("Grimer", 160, 14, 21, 2, "Grimer.png", "Poison"));
MasterDeck.push(CreateCard("Muk", 320, 35, 40, 5, "Muk.png", "Poison"));
MasterDeck.push(CreateCard("Shelder", 150, 15, 18, 2,"Shelder.png", "Ice"));
MasterDeck.push(CreateCard("Cloyster", 300, 25, 38, 5, "Cloyster.png", "Ice"));
MasterDeck.push(CreateCard("Ghastly", 140, 16, 10, 4, "Ghastly.png", "Ghost"));
MasterDeck.push(CreateCard("Haunter", 250, 25, 18, 6, "Haunter.png", "Ghost"));
MasterDeck.push(CreateCard("Gengar", 350, 40, 28, 8 ,"Gengar.png", "Ghost"));
MasterDeck.push(CreateCard("Onix", 160, 15, 30, 5,  "Onix.png", "Rock"));
MasterDeck.push(CreateCard("Drowzee", 150, 16, 20, 3,  "Drowzee.png", "Psychic"));
MasterDeck.push(CreateCard("Hypno", 300, 25, 35 , 5, "Hypno.png", "Psychic"));
MasterDeck.push(CreateCard("Krabby", 140, 15, 15, 3,"Krabby.png", "Water"));
MasterDeck.push(CreateCard("Kingler", 300, 28, 30, 5, "Kingler.png", "Water"));
MasterDeck.push(CreateCard("Voltorb", 140, 14, 12, 3, "Voltorb.png", "Electric"));
MasterDeck.push(CreateCard("Electrode", 300, 28, 25, 5, "Electrode.png", "Electric"));
MasterDeck.push(CreateCard("Exeggcute", 130, 15, 15, 3, "Exeggcute.png", "Grass"));
MasterDeck.push(CreateCard("Exeggutor", 320, 30, 35, 6, "Exeggutor.png", "Psychic" ));
MasterDeck.push(CreateCard("Cubone", 150, 16, 16, 3, "Cubone.png", "Ground"));
MasterDeck.push(CreateCard("Marowak", 300, 25, 30, 5, "Marowak.png", "Ground"));
MasterDeck.push(CreateCard("Hitmonlee", 250, 25, 30, 6,"Hitmonlee.png", "Fighting"));
MasterDeck.push(CreateCard("Hitmonchan", 250, 25, 30, 6, "Hitmonchan.png", "Fighting"));
MasterDeck.push(CreateCard("Normal", 300, 18, 35, 7, "Lickitung.png", "Normal"));
MasterDeck.push(CreateCard("Koffing", 150, 16, 20, 3, "Koffing.png", "Poison"));
MasterDeck.push(CreateCard("Weezing", 320, 25, 40, 6, "Weezing.png", "Poison"));
MasterDeck.push(CreateCard("Rhyhorn", 170, 15, 20, 3, "Rhyhorn.png", "Rock"));
MasterDeck.push(CreateCard("Rhydon", 380, 30, 40, 6, "Rhydon.png", "Rock"));
MasterDeck.push(CreateCard("Chansey", 400, 15, 50, 7, "Chansey.png", "Dragon"));
MasterDeck.push(CreateCard("Tangela", 250, 21, 35, 5, "Tangela.png", "Grass"));
MasterDeck.push(CreateCard("Kangashkan", 300, 25, 35, 6, "Kangashkan.png", "Fighting"));
MasterDeck.push(CreateCard("Horsea", 180, 16, 13, 3, "Horsea.png", "Dragon"));
MasterDeck.push(CreateCard("Seadra", 300, 25, 25, 5, "Seadra.png", "Dragon"));
MasterDeck.push(CreateCard("Kingdra", 400, 40, 40, 7, "Kingdra.png", "Dragon"));
MasterDeck.push(CreateCard("Goldeen", 160, 15, 18, 2,  "Goldeen.png", "Water"));
MasterDeck.push(CreateCard("Seaking", 320, 25, 35, 5, "Seaking.png", "Water"));
MasterDeck.push(CreateCard("Staryu", 180, 16, 18, 3, "Staryu", "Psychic"));
MasterDeck.push(CreateCard("Starmie", 320, 30, 40, 6, "Starmie.png", "Psychic"));
MasterDeck.push(CreateCard("Mr/.Mime", 250, 25, 40, 6,  "MrMime.png", "Psychic"));
MasterDeck.push(CreateCard("Scyther", 250, 25, 20, 7, "Scyther.png", "Bug"));
MasterDeck.push(CreateCard("Jynx", 250, 25, 20, 6, "Jynx.png", "Ice" ));
MasterDeck.push(CreateCard("Electabuzz", 250, 25, 30, 6, "Electabuzz.png", "Electric"));
MasterDeck.push(CreateCard("Magmar", 250, 25, 25, 7, "Magmar.png", "Fire"));
MasterDeck.push(CreateCard("Pinsir", 250, 25, 25, 6, "Pinsir.png", "Bug"));
MasterDeck.push(CreateCard("Tauros", 300, 25,  35, 6, "Tauros.png", "Normal"));
MasterDeck.push(CreateCard("Magikarp", 100, 10, 10, 1, "Magikarp.png", "Water"));
MasterDeck.push(CreateCard("Gyarados", 400, 40, 40, 8, "Gyarados.png", "Dragon"));
MasterDeck.push(CreateCard("Lapras", 300, 30, 45, 7, "Lapras.png", "Ice"));
MasterDeck.push(CreateCard("Ditto", 250, 25, 25, 7, "Ditto.png", "Dragon"));
MasterDeck.push(CreateCard("Eevee", 180, 15, 15, 3, "Eevee.png", "Normal"));
MasterDeck.push(CreateCard("Flareon", 350, 30, 30 ,6, "Flareon.png", "Fire"));
MasterDeck.push(CreateCard("Vaporeon", 350, 30, 30, 6, "Vaporeon.png", "Water"));
MasterDeck.push(CreateCard("Jolteon", 350, 30, 30, 6, "Jolteon.png", "Electric"));
MasterDeck.push(CreatCard("Porygon", 300, 21, 35, 7, "Porygon.png", "Dragon"));
MasterDeck.push(CreateCard("Omanyte", 180, 15, 20, 3, "Omanyte.png", "Water"));
MasterDeck.push(CreateCard("Omastar", 350, 30, 40, 5, "Omastar.png", "Water"));
MasterDeck.push(CreateCard("Kabuto", 160, 18, 15, 3, "Kabuto.png", "Rock" ));
MasterDeck.push(CreateCard("Kabutops", 350, 30, 30, 7, "Kabutops.png", "Rock"));
MasterDeck.push(CreateCard("Aerodactyle", 300, 30, 35, 8, "Aerodactyle.png", "Rock" , "Dragon"));
MasterDeck.push(CreateCard("Snorlax", 500, 25, 50, 7, "Snorlax.png", "Dragon"));
MasterDeck.push(CreateCard("Arcticuno", 400, 35, 30, 6, "Arcticuno.png", "Ice" , "Dragon"));
MasterDeck.push(CreateCard("Zapdos", 400, 35, 30, 6,  "Zapdos.png", "Electric" , "Dragon"));
MasterDeck.push(CreateCard("Moltres", 400, 35, 30, 6, "Moltres.png", "Fire" , "Dragon" ));
MasterDeck.push(CreateCard("Dratini", 200, 18, 18, 4, "Dratini.png", "Dragon"));
MasterDeck.push(CreateCard("Dragonair", 300, 28, 28, 5, "Dragonair.png", "Dragon"));
MasterDeck.push(CreateCard("Dragonite", 500, 40, 40, 8, "Dragonite.png", "Dragon"));
MasterDeck.push(CreateCard("Mewtwo", 500, 45, "Mewtwo.png", "Psychic"));
MasterDeck.push(CreateCard("Mew", 800, 50, "Mew.png", "Dragon"));



return MasterDeck;
}